classdef dropout_torchmangle7_Dropout < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %dropout_torchmangle7_Dropout Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:42

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_4
        Constant_3



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = dropout_torchmangle7_Dropout(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [dropout_5, dropout_5_rank] = predict(obj,dropout_argument1_1, dropout_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [dropout_argument1_1, dropout_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(dropout_argument1_1, '', numel(dropout_argument1_1_rank));
            [dropout_argument1_1] = struct('value', dropout_argument1_1, 'rank', int64(numel(dropout_argument1_1_rank)));

            [dropout_5] = tracedPyTorchFunction(obj,dropout_argument1_1,false,"predict");

            [dropout_5_rank] = ones([1,dropout_5.rank], 'single');
            dropout_5_rank = dlarray(dropout_5_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(dropout_5.value) == 'U'))
                dropout_5 = permute(dropout_5.value, fliplr(1:max(2,dropout_5.rank)));
            end

        end



        function [dropout_5, dropout_5_rank] = forward(obj,dropout_argument1_1, dropout_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [dropout_argument1_1, dropout_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(dropout_argument1_1, '', numel(dropout_argument1_1_rank));
            [dropout_argument1_1] = struct('value', dropout_argument1_1, 'rank', int64(numel(dropout_argument1_1_rank)));

            [dropout_5] = tracedPyTorchFunction(obj,dropout_argument1_1,true,"forward");

            [dropout_5_rank] = ones([1,dropout_5.rank], 'single');
            dropout_5_rank = dlarray(dropout_5_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(dropout_5.value) == 'U'))
                dropout_5 = permute(dropout_5.value, fliplr(1:max(2,dropout_5.rank)));
            end

        end



        function [dropout_5] = tracedPyTorchFunction(obj,dropout_argument1_1,isForward,predict)

            [Constant_4] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_4), int64(0), "Typed");
            [Constant_3] = empty_model_traced_mf.ops.makeStructForConstant(single(obj.Constant_3), int64(0), "Typed");
            [dropout_5] = empty_model_traced_mf.ops.pyDropout(dropout_argument1_1, Constant_3, isForward);
        end

    end
end

