classdef linear_torchmangle1_Linear < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %linear_torchmangle1_Linear Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:41

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_6



    end

    properties (Learnable)
        % Trainable Parameters
        Param_weight
    end

    methods
        function obj = linear_torchmangle1_Linear(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [linear_7] = predict(obj,linear_input_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(linear_input_1, '', 3);
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(3));

            [linear_7] = tracedPyTorchFunction(obj,linear_input_1,false,"predict");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_7.value) == 'U'))
                linear_7 = permute(linear_7.value, fliplr(1:max(2,linear_7.rank)));
            end

        end



        function [linear_7] = forward(obj,linear_input_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(linear_input_1, '', 3);
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(3));

            [linear_7] = tracedPyTorchFunction(obj,linear_input_1,true,"forward");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_7.value) == 'U'))
                linear_7 = permute(linear_7.value, fliplr(1:max(2,linear_7.rank)));
            end

        end



        function [linear_7] = tracedPyTorchFunction(obj,linear_input_1,isForward,predict)

            [Constant_6] = empty_model_traced_mf.ops.makeStructForConstant(double(obj.Constant_6), int64(0), "Typed");
            GetAttr_weight_1 = obj.Param_weight;

            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UU'), 'rank', 2);

            [linear_7] = empty_model_traced_mf.ops.pyLinear(linear_input_1, GetAttr_weight_1, Constant_6);
        end

    end
end

