classdef modules_sparse_Embedding < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %modules_sparse_Embedding Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:41

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_7
        Constant_6



    end

    properties (Learnable)
        % Trainable Parameters
        Param_weight
    end

    methods
        function obj = modules_sparse_Embedding(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [embedding_9, embedding_9_rank] = predict(obj,embedding_input_1, embedding_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [embedding_input_1, embedding_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(embedding_input_1, '', numel(embedding_input_1_rank));
            [embedding_input_1] = struct('value', embedding_input_1, 'rank', int64(numel(embedding_input_1_rank)));

            [embedding_9] = tracedPyTorchFunction(obj,embedding_input_1,false,"predict");

            [embedding_9_rank] = ones([1,embedding_9.rank], 'single');
            embedding_9_rank = dlarray(embedding_9_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(embedding_9.value) == 'U'))
                embedding_9 = permute(embedding_9.value, fliplr(1:max(2,embedding_9.rank)));
            end

        end



        function [embedding_9, embedding_9_rank] = forward(obj,embedding_input_1, embedding_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [embedding_input_1, embedding_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(embedding_input_1, '', numel(embedding_input_1_rank));
            [embedding_input_1] = struct('value', embedding_input_1, 'rank', int64(numel(embedding_input_1_rank)));

            [embedding_9] = tracedPyTorchFunction(obj,embedding_input_1,true,"forward");

            [embedding_9_rank] = ones([1,embedding_9.rank], 'single');
            embedding_9_rank = dlarray(embedding_9_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(embedding_9.value) == 'U'))
                embedding_9 = permute(embedding_9.value, fliplr(1:max(2,embedding_9.rank)));
            end

        end



        function [embedding_9] = tracedPyTorchFunction(obj,embedding_input_1,isForward,predict)

            [Constant_7] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_7), int64(0), "Typed");
            [Constant_6] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_6), int64(0), "Typed");
            GetAttr_weight_1 = obj.Param_weight;

            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UU'), 'rank', 2);

            [embedding_9] = empty_model_traced_mf.ops.pyEmbedding(GetAttr_weight_1, embedding_input_1, Constant_6, Constant_7, Constant_7);
        end

    end
end

