classdef modules_activation_GELU < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %modules_activation_GELU Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:42

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_3



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = modules_activation_GELU(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [gelu_4, gelu_4_rank] = predict(obj,gelu_argument1_1, gelu_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [gelu_argument1_1, gelu_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(gelu_argument1_1, '', numel(gelu_argument1_1_rank));
            [gelu_argument1_1] = struct('value', gelu_argument1_1, 'rank', int64(numel(gelu_argument1_1_rank)));

            [gelu_4] = tracedPyTorchFunction(obj,gelu_argument1_1,false,"predict");

            [gelu_4_rank] = ones([1,gelu_4.rank], 'single');
            gelu_4_rank = dlarray(gelu_4_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(gelu_4.value) == 'U'))
                gelu_4 = permute(gelu_4.value, fliplr(1:max(2,gelu_4.rank)));
            end

        end



        function [gelu_4, gelu_4_rank] = forward(obj,gelu_argument1_1, gelu_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [gelu_argument1_1, gelu_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(gelu_argument1_1, '', numel(gelu_argument1_1_rank));
            [gelu_argument1_1] = struct('value', gelu_argument1_1, 'rank', int64(numel(gelu_argument1_1_rank)));

            [gelu_4] = tracedPyTorchFunction(obj,gelu_argument1_1,true,"forward");

            [gelu_4_rank] = ones([1,gelu_4.rank], 'single');
            gelu_4_rank = dlarray(gelu_4_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(gelu_4.value) == 'U'))
                gelu_4 = permute(gelu_4.value, fliplr(1:max(2,gelu_4.rank)));
            end

        end



        function [gelu_4] = tracedPyTorchFunction(obj,gelu_argument1_1,isForward,predict)

            [Constant_3] = empty_model_traced_mf.ops.makeStructForConstant(string(obj.Constant_3), int64(0), "Typed");
            [gelu_4] = empty_model_traced_mf.ops.pyGelu(gelu_argument1_1, Constant_3);
        end

    end
end

