classdef TopLevelModule_ATEN3 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %TopLevelModule_ATEN3 Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:42

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_27
        Constant_37
        Constant_69
        Constant_34
        Constant_30
        Constant_33



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = TopLevelModule_ATEN3(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [unsqueeze_input_1, unsqueeze_input_1_rank] = predict(obj,size_batchu_1)

            %Validates that the input has the correct format and permutes its dimensions into the reverse of the original PyTorch format.
            empty_model_traced_mf.ops.validateInput(size_batchu_1,3);
            [size_batchu_1, size_batchu_1_format] = empty_model_traced_mf.ops.permuteInputToReversePyTorch(size_batchu_1, 3);
            [size_batchu_1] = struct('value', size_batchu_1, 'rank', int64(3));

            [unsqueeze_input_1] = tracedPyTorchFunction(obj,size_batchu_1,false,"predict");

            [unsqueeze_input_1_rank] = ones([1,unsqueeze_input_1.rank], 'single');
            unsqueeze_input_1_rank = dlarray(unsqueeze_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(unsqueeze_input_1.value) == 'U'))
                unsqueeze_input_1 = permute(unsqueeze_input_1.value, fliplr(1:max(2,unsqueeze_input_1.rank)));
            end

        end



        function [unsqueeze_input_1, unsqueeze_input_1_rank] = forward(obj,size_batchu_1)

            %Validates that the input has the correct format and permutes its dimensions into the reverse of the original PyTorch format.
            empty_model_traced_mf.ops.validateInput(size_batchu_1,3);
            [size_batchu_1, size_batchu_1_format] = empty_model_traced_mf.ops.permuteInputToReversePyTorch(size_batchu_1, 3);
            [size_batchu_1] = struct('value', size_batchu_1, 'rank', int64(3));

            [unsqueeze_input_1] = tracedPyTorchFunction(obj,size_batchu_1,true,"forward");

            [unsqueeze_input_1_rank] = ones([1,unsqueeze_input_1.rank], 'single');
            unsqueeze_input_1_rank = dlarray(unsqueeze_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(unsqueeze_input_1.value) == 'U'))
                unsqueeze_input_1 = permute(unsqueeze_input_1.value, fliplr(1:max(2,unsqueeze_input_1.rank)));
            end

        end



        function [unsqueeze_input_1] = tracedPyTorchFunction(obj,size_batchu_1,isForward,predict)

            [Constant_27] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_27), int64(0), "Typed");
            [size_28] = empty_model_traced_mf.ops.pySize(size_batchu_1, Constant_27);
            [NumToTensor_t_1] = empty_model_traced_mf.ops.makeStructForConstant(single(size_28.value), int64([size_28.rank]), "Tensor");
            [ScalarImplicit_32] = empty_model_traced_mf.ops.pyScalarImplicit(NumToTensor_t_1);
            [Constant_37] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_37), int64(0), "Typed");
            [Constant_69] = empty_model_traced_mf.ops.makeStructForConstant(string(obj.Constant_69), int64(0), "Typed");
            [Constant_34] = empty_model_traced_mf.ops.makeStructForConstant(double(obj.Constant_34), int64(0), "Typed");
            [Constant_30] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_30), int64(0), "Typed");
            [Constant_33] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_33), int64(0), "Typed");
            [arange_38] = empty_model_traced_mf.ops.pyArange(Constant_30, ScalarImplicit_32, struct('value', 1, 'rank', 0), Constant_33);
            [unsqueeze_input_1] = empty_model_traced_mf.ops.pyUnsqueeze(arange_38, Constant_30);
        end

    end
end

