classdef TopLevelModule_ATEN4 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %TopLevelModule_ATEN4 Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:42

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_27



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = TopLevelModule_ATEN4(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 3;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [add_input0_1, add_input0_1_rank] = predict(obj,add_43, add_46, add_46_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_43, add_43_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_43, '', 3);

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_46, add_46_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_46, '', numel(add_46_rank));
            [add_43] = struct('value', add_43, 'rank', int64(3));
            [add_46] = struct('value', add_46, 'rank', int64(numel(add_46_rank)));

            [add_input0_1] = tracedPyTorchFunction(obj,add_43, add_46,false,"predict");

            [add_input0_1_rank] = ones([1,add_input0_1.rank], 'single');
            add_input0_1_rank = dlarray(add_input0_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_input0_1.value) == 'U'))
                add_input0_1 = permute(add_input0_1.value, fliplr(1:max(2,add_input0_1.rank)));
            end

        end



        function [add_input0_1, add_input0_1_rank] = forward(obj,add_43, add_46, add_46_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_43, add_43_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_43, '', 3);

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_46, add_46_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_46, '', numel(add_46_rank));
            [add_43] = struct('value', add_43, 'rank', int64(3));
            [add_46] = struct('value', add_46, 'rank', int64(numel(add_46_rank)));

            [add_input0_1] = tracedPyTorchFunction(obj,add_43, add_46,true,"forward");

            [add_input0_1_rank] = ones([1,add_input0_1.rank], 'single');
            add_input0_1_rank = dlarray(add_input0_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_input0_1.value) == 'U'))
                add_input0_1 = permute(add_input0_1.value, fliplr(1:max(2,add_input0_1.rank)));
            end

        end



        function [add_input0_1] = tracedPyTorchFunction(obj,add_43, add_46,isForward,predict)

            [Constant_27] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_27), int64(0), "Typed");
            [add_input0_1] = empty_model_traced_mf.ops.pyElementwiseBinary(add_43, add_46, 'plus', Constant_27);
        end

    end
end

