classdef torch_transformerzerostepMF_CausalSelfAttention < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %torch_transformerzerostepMF_CausalSelfAttention Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:41

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_c_attn
        Param_attn_dropout
        Param_c_proj
        Param_resid_dropout
    end

    properties
        % Non-Trainable Parameters
        Constant_158
        Constant_155
        Constant_134
        Constant_92
        Constant_13
        Constant_29
        Constant_51
        Constant_61
        Constant_68
        Constant_78
        Constant_88
        Constant_129
        Constant_130
        Constant_146


        Param_bias
    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = torch_transformerzerostepMF_CausalSelfAttention(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_179] = predict(obj,size_argument1_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(numel(size_argument1_1_rank)));

            [CallMethod_179] = tracedPyTorchFunction(obj,size_argument1_1,false,"predict");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(CallMethod_179.value) == 'U'))
                CallMethod_179 = permute(CallMethod_179.value, fliplr(1:max(2,CallMethod_179.rank)));
            end

        end



        function [CallMethod_179] = forward(obj,size_argument1_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(numel(size_argument1_1_rank)));

            [CallMethod_179] = tracedPyTorchFunction(obj,size_argument1_1,true,"forward");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(CallMethod_179.value) == 'U'))
                CallMethod_179 = permute(CallMethod_179.value, fliplr(1:max(2,CallMethod_179.rank)));
            end

        end



        function [CallMethod_179] = tracedPyTorchFunction(obj,size_argument1_1,isForward,predict)

            [Constant_158] = empty_model_traced_mf.ops.makeStructForConstant(double(obj.Constant_158), int64(0), "Typed");
            [Constant_155] = empty_model_traced_mf.ops.makeStructForConstant(single(obj.Constant_155), int64(0), "Typed");
            [Constant_134] = empty_model_traced_mf.ops.makeStructForConstant(single(obj.Constant_134), int64([0]), "Tensor");
            [Constant_92] = empty_model_traced_mf.ops.makeStructForConstant(single(obj.Constant_92), int64([0]), "Tensor");
            [Constant_13] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_13), int64(0), "Typed");
            [Constant_29] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_29), int64(0), "Typed");
            [Constant_51] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_51), int64(0), "Typed");
            [Constant_61] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_61), int64(0), "Typed");
            [Constant_68] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_68), int64(0), "Typed");
            [Constant_78] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_78), int64(0), "Typed");
            [Constant_88] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_88), int64(0), "Typed");
            [Constant_129] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_129), int64(0), "Typed");
            [Constant_130] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_130), int64(0), "Typed");
            [Constant_146] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_146), int64(0), "Typed");
            GetAttr_residdropout_1 = obj.Param_resid_dropout;


            GetAttr_cproj_1 = obj.Param_c_proj;


            GetAttr_attndropout_1 = obj.Param_attn_dropout;


            GetAttr_bias_1 = obj.Param_bias;

            [GetAttr_bias_1] = struct('value', dlarray(GetAttr_bias_1,'UUUU'), 'rank', 4);

            GetAttr_cattn_1 = obj.Param_c_attn;


            [size_14] = empty_model_traced_mf.ops.pySize(size_argument1_1, Constant_13);
            [NumToTensor_B_1] = empty_model_traced_mf.ops.makeStructForConstant(single(size_14.value), int64([size_14.rank]), "Tensor");
            [Int_18] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_B_1.value, int64([NumToTensor_B_1.rank]), "Integer");
            [Int_21] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_B_1.value, int64([NumToTensor_B_1.rank]), "Integer");
            [Int_24] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_B_1.value, int64([NumToTensor_B_1.rank]), "Integer");
            [Int_27] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_B_1.value, int64([NumToTensor_B_1.rank]), "Integer");
            [size_30] = empty_model_traced_mf.ops.pySize(size_argument1_1, Constant_29);
            [NumToTensor_T_1] = empty_model_traced_mf.ops.makeStructForConstant(single(size_30.value), int64([size_30.rank]), "Tensor");
            [Int_34] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_T_1.value, int64([NumToTensor_T_1.rank]), "Integer");
            [Int_37] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_T_1.value, int64([NumToTensor_T_1.rank]), "Integer");
            [Int_40] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_T_1.value, int64([NumToTensor_T_1.rank]), "Integer");
            [Int_43] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_T_1.value, int64([NumToTensor_T_1.rank]), "Integer");
            [Int_46] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_T_1.value, int64([NumToTensor_T_1.rank]), "Integer");
            [Int_49] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_T_1.value, int64([NumToTensor_T_1.rank]), "Integer");
            [size_52] = empty_model_traced_mf.ops.pySize(size_argument1_1, Constant_51);
            [NumToTensor_C_1] = empty_model_traced_mf.ops.makeStructForConstant(single(size_52.value), int64([size_52.rank]), "Tensor");
            [Int_56] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_C_1.value, int64([NumToTensor_C_1.rank]), "Integer");

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            [CallMethod_59,CallMethod_59_rank] = GetAttr_cattn_1.(predict)(size_argument1_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'));
            [CallMethod_59, CallMethod_59_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(CallMethod_59, '', int64(numel(CallMethod_59_rank)));
            if ~contains(CallMethod_59_format,'U')
                [CallMethod_59] = struct('value', CallMethod_59, 'rank', numel(CallMethod_59_format));
            else
                [CallMethod_59] = struct('value', CallMethod_59, 'rank', int64(numel(CallMethod_59_rank)));
            end

            [slice_63] = empty_model_traced_mf.ops.pySlice(CallMethod_59, Constant_13, Constant_13, Constant_61, Constant_29, false);
            [slice_66] = empty_model_traced_mf.ops.pySlice(slice_63, Constant_29, Constant_13, Constant_61, Constant_29, false);
            [slice_q_1] = empty_model_traced_mf.ops.pySlice(slice_66, Constant_51, Constant_13, Constant_68, Constant_29, false);
            [slice_73] = empty_model_traced_mf.ops.pySlice(CallMethod_59, Constant_13, Constant_13, Constant_61, Constant_29, false);
            [slice_76] = empty_model_traced_mf.ops.pySlice(slice_73, Constant_29, Constant_13, Constant_61, Constant_29, false);
            [slice_k_1] = empty_model_traced_mf.ops.pySlice(slice_76, Constant_51, Constant_68, Constant_78, Constant_29, false);
            [slice_83] = empty_model_traced_mf.ops.pySlice(CallMethod_59, Constant_13, Constant_13, Constant_61, Constant_29, false);
            [slice_86] = empty_model_traced_mf.ops.pySlice(slice_83, Constant_29, Constant_13, Constant_61, Constant_29, false);
            [slice_v_1] = empty_model_traced_mf.ops.pySlice(slice_86, Constant_51, Constant_78, Constant_88, Constant_29, false);
            [floordivide_93] = empty_model_traced_mf.ops.pyElementwiseBinary(NumToTensor_C_1, Constant_92, '@(x, y)floor(rdivide(x, y))');
            [Int_95] = empty_model_traced_mf.ops.makeStructForConstant(floordivide_93.value, int64([floordivide_93.rank]), "Integer");
            [ListConstruct_100] = empty_model_traced_mf.ops.pyListConstruct(Int_27, Int_49, Constant_29, Int_95);
            [view_101] = empty_model_traced_mf.ops.pyView(slice_k_1, ListConstruct_100);
            [transpose_k0_1] = empty_model_traced_mf.ops.pyTranspose(view_101, Constant_29, Constant_51);
            [floordivide_105] = empty_model_traced_mf.ops.pyElementwiseBinary(NumToTensor_C_1, Constant_92, '@(x, y)floor(rdivide(x, y))');
            [Int_107] = empty_model_traced_mf.ops.makeStructForConstant(floordivide_105.value, int64([floordivide_105.rank]), "Integer");
            [ListConstruct_112] = empty_model_traced_mf.ops.pyListConstruct(Int_24, Int_46, Constant_29, Int_107);
            [view_113] = empty_model_traced_mf.ops.pyView(slice_q_1, ListConstruct_112);
            [transpose_q0_1] = empty_model_traced_mf.ops.pyTranspose(view_113, Constant_29, Constant_51);
            [floordivide_117] = empty_model_traced_mf.ops.pyElementwiseBinary(NumToTensor_C_1, Constant_92, '@(x, y)floor(rdivide(x, y))');
            [Int_119] = empty_model_traced_mf.ops.makeStructForConstant(floordivide_117.value, int64([floordivide_117.rank]), "Integer");
            [ListConstruct_124] = empty_model_traced_mf.ops.pyListConstruct(Int_21, Int_43, Constant_29, Int_119);
            [view_125] = empty_model_traced_mf.ops.pyView(slice_v_1, ListConstruct_124);
            [transpose_v0_1] = empty_model_traced_mf.ops.pyTranspose(view_125, Constant_29, Constant_51);
            [transpose_131] = empty_model_traced_mf.ops.pyTranspose(transpose_k0_1, Constant_129, Constant_130);
            [matmul_132] = empty_model_traced_mf.ops.pyMatmul(transpose_q0_1, transpose_131);
            [mul_att_1] = empty_model_traced_mf.ops.pyElementwiseBinary(matmul_132, Constant_134, 'times');
            [slice_138] = empty_model_traced_mf.ops.pySlice(GetAttr_bias_1, Constant_13, Constant_13, Constant_61, Constant_29, false);
            [slice_141] = empty_model_traced_mf.ops.pySlice(slice_138, Constant_29, Constant_13, Constant_61, Constant_29, false);
            [slice_145] = empty_model_traced_mf.ops.pySlice(slice_141, Constant_51, Constant_13, Int_40, Constant_29, false);
            [slice_149] = empty_model_traced_mf.ops.pySlice(slice_145, Constant_146, Constant_13, Int_37, Constant_29, false);
            [eq_152] = empty_model_traced_mf.ops.pyEq(slice_149, Constant_13);
            [maskedfill_input_1] = empty_model_traced_mf.ops.pyMaskedFill(mul_att_1, eq_152, Constant_155);
            [softmax_input1_1] = empty_model_traced_mf.ops.pySoftmax(maskedfill_input_1, Constant_130);

            softmax_input1_1_labelled = softmax_input1_1;
            softmax_input1_1_labelled.value = permute(softmax_input1_1_labelled.value, fliplr(1:max(2,softmax_input1_1_labelled.rank)));
            [CallMethod_162,CallMethod_162_rank] = GetAttr_attndropout_1.(predict)(softmax_input1_1_labelled.value,dlarray(ones(1,softmax_input1_1.rank),'UU'));
            [CallMethod_162, CallMethod_162_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(CallMethod_162, '', int64(numel(CallMethod_162_rank)));
            if ~contains(CallMethod_162_format,'U')
                [CallMethod_162] = struct('value', CallMethod_162, 'rank', numel(CallMethod_162_format));
            else
                [CallMethod_162] = struct('value', CallMethod_162, 'rank', int64(numel(CallMethod_162_rank)));
            end

            [matmul_y_1] = empty_model_traced_mf.ops.pyMatmul(CallMethod_162, transpose_v0_1);
            [transpose_166] = empty_model_traced_mf.ops.pyTranspose(matmul_y_1, Constant_29, Constant_51);
            contiguous_168 = transpose_166;
            [ListConstruct_173] = empty_model_traced_mf.ops.pyListConstruct(Int_18, Int_34, Int_56);
            [view_input2_1] = empty_model_traced_mf.ops.pyView(contiguous_168, ListConstruct_173);

            view_input2_1_labelled = view_input2_1;
            view_input2_1_labelled.value = permute(view_input2_1_labelled.value, fliplr(1:max(2,view_input2_1_labelled.rank)));
            [CallMethod_178] = GetAttr_cproj_1.(predict)(view_input2_1_labelled.value);
            [CallMethod_178, CallMethod_178_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(CallMethod_178, '', int64(3));
            if ~contains(CallMethod_178_format,'U')
                [CallMethod_178] = struct('value', CallMethod_178, 'rank', numel(CallMethod_178_format));
            else
                [CallMethod_178] = struct('value', CallMethod_178, 'rank', int64(3));
            end


            CallMethod_178_labelled = CallMethod_178;
            CallMethod_178_labelled.value = permute(CallMethod_178_labelled.value, fliplr(1:max(2,CallMethod_178_labelled.rank)));
            [CallMethod_179] = GetAttr_residdropout_1.(predict)(CallMethod_178_labelled.value);
            [CallMethod_179, CallMethod_179_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(CallMethod_179, '', int64(3));
            if ~contains(CallMethod_179_format,'U')
                [CallMethod_179] = struct('value', CallMethod_179, 'rank', numel(CallMethod_179_format));
            else
                [CallMethod_179] = struct('value', CallMethod_179, 'rank', int64(3));
            end

        end

    end
end

