classdef transformerzerostepMF_torchmangle4_LayerNorm < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %transformerzerostepMF_torchmangle4_LayerNorm Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:42

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_16
        Constant_15
        Constant_14
        Constant_5



    end

    properties (Learnable)
        % Trainable Parameters
        Param_weight
    end

    methods
        function obj = transformerzerostepMF_torchmangle4_LayerNorm(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [layernorm_input0_1, layernorm_input0_1_rank] = predict(obj,layernorm_input_1, layernorm_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [layernorm_input_1, layernorm_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(layernorm_input_1, '', numel(layernorm_input_1_rank));
            [layernorm_input_1] = struct('value', layernorm_input_1, 'rank', int64(numel(layernorm_input_1_rank)));

            [layernorm_input0_1] = tracedPyTorchFunction(obj,layernorm_input_1,false,"predict");

            [layernorm_input0_1_rank] = ones([1,layernorm_input0_1.rank], 'single');
            layernorm_input0_1_rank = dlarray(layernorm_input0_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(layernorm_input0_1.value) == 'U'))
                layernorm_input0_1 = permute(layernorm_input0_1.value, fliplr(1:max(2,layernorm_input0_1.rank)));
            end

        end



        function [layernorm_input0_1, layernorm_input0_1_rank] = forward(obj,layernorm_input_1, layernorm_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [layernorm_input_1, layernorm_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(layernorm_input_1, '', numel(layernorm_input_1_rank));
            [layernorm_input_1] = struct('value', layernorm_input_1, 'rank', int64(numel(layernorm_input_1_rank)));

            [layernorm_input0_1] = tracedPyTorchFunction(obj,layernorm_input_1,true,"forward");

            [layernorm_input0_1_rank] = ones([1,layernorm_input0_1.rank], 'single');
            layernorm_input0_1_rank = dlarray(layernorm_input0_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(layernorm_input0_1.value) == 'U'))
                layernorm_input0_1 = permute(layernorm_input0_1.value, fliplr(1:max(2,layernorm_input0_1.rank)));
            end

        end



        function [layernorm_input0_1] = tracedPyTorchFunction(obj,layernorm_input_1,isForward,predict)

            [Constant_16] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_16), int64(0), "Typed");
            [Constant_15] = empty_model_traced_mf.ops.makeStructForConstant(single(obj.Constant_15), int64(0), "Typed");
            [Constant_14] = empty_model_traced_mf.ops.makeStructForConstant(double(obj.Constant_14), int64(0), "Typed");
            [Constant_5] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_5), int64(0), "Typed");
            GetAttr_weight_1 = obj.Param_weight;

            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UU'), 'rank', 1);

            [size_6] = empty_model_traced_mf.ops.pySize(GetAttr_weight_1, Constant_5);
            [NumToTensor_7] = empty_model_traced_mf.ops.makeStructForConstant(single(size_6.value), int64([size_6.rank]), "Tensor");
            [Int_11] = empty_model_traced_mf.ops.makeStructForConstant(NumToTensor_7.value, int64([NumToTensor_7.rank]), "Integer");
            [ListConstruct_12] = empty_model_traced_mf.ops.pyListConstruct(Int_11);
            [layernorm_input0_1] = empty_model_traced_mf.ops.pyLayerNorm(layernorm_input_1, ListConstruct_12, GetAttr_weight_1, Constant_14, Constant_15);
        end

    end
end

