classdef x0_ATEN2 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %x0_ATEN2 Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:42

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_17



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = x0_ATEN2(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 4;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [add_27, add_27_rank] = predict(obj,add_input_1, add_23, add_input_1_rank, add_23_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_input_1, add_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_input_1, '', numel(add_input_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_23, add_23_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_23, '', numel(add_23_rank));
            [add_input_1] = struct('value', add_input_1, 'rank', int64(numel(add_input_1_rank)));
            [add_23] = struct('value', add_23, 'rank', int64(numel(add_23_rank)));

            [add_27] = tracedPyTorchFunction(obj,add_input_1, add_23,false,"predict");

            [add_27_rank] = ones([1,add_27.rank], 'single');
            add_27_rank = dlarray(add_27_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_27.value) == 'U'))
                add_27 = permute(add_27.value, fliplr(1:max(2,add_27.rank)));
            end

        end



        function [add_27, add_27_rank] = forward(obj,add_input_1, add_23, add_input_1_rank, add_23_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_input_1, add_input_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_input_1, '', numel(add_input_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_23, add_23_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_23, '', numel(add_23_rank));
            [add_input_1] = struct('value', add_input_1, 'rank', int64(numel(add_input_1_rank)));
            [add_23] = struct('value', add_23, 'rank', int64(numel(add_23_rank)));

            [add_27] = tracedPyTorchFunction(obj,add_input_1, add_23,true,"forward");

            [add_27_rank] = ones([1,add_27.rank], 'single');
            add_27_rank = dlarray(add_27_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_27.value) == 'U'))
                add_27 = permute(add_27.value, fliplr(1:max(2,add_27.rank)));
            end

        end



        function [add_27] = tracedPyTorchFunction(obj,add_input_1, add_23,isForward,predict)

            [Constant_17] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_17), int64(0), "Typed");
            [add_27] = empty_model_traced_mf.ops.pyElementwiseBinary(add_input_1, add_23, 'plus', Constant_17);
        end

    end
end

