classdef x0_ATEN1 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %x0_ATEN1 Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jun-2025 11:56:42

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_17



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = x0_ATEN1(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 3;
            obj.NumOutputs = 3;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [add_input_1, add_input_1_rank] = predict(obj,add_argument1_1, add_14, add_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_argument1_1, add_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_argument1_1, '', numel(add_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_14, add_14_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_14, '', 3);
            [add_argument1_1] = struct('value', add_argument1_1, 'rank', int64(numel(add_argument1_1_rank)));
            [add_14] = struct('value', add_14, 'rank', int64(3));

            [add_input_1] = tracedPyTorchFunction(obj,add_argument1_1, add_14,false,"predict");

            [add_input_1_rank] = ones([1,add_input_1.rank], 'single');
            add_input_1_rank = dlarray(add_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_input_1.value) == 'U'))
                add_input_1 = permute(add_input_1.value, fliplr(1:max(2,add_input_1.rank)));
            end

        end



        function [add_input_1, add_input_1_rank] = forward(obj,add_argument1_1, add_14, add_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_argument1_1, add_argument1_1_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_argument1_1, '', numel(add_argument1_1_rank));

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_14, add_14_format] = empty_model_traced_mf.ops.permuteToReversePyTorch(add_14, '', 3);
            [add_argument1_1] = struct('value', add_argument1_1, 'rank', int64(numel(add_argument1_1_rank)));
            [add_14] = struct('value', add_14, 'rank', int64(3));

            [add_input_1] = tracedPyTorchFunction(obj,add_argument1_1, add_14,true,"forward");

            [add_input_1_rank] = ones([1,add_input_1.rank], 'single');
            add_input_1_rank = dlarray(add_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_input_1.value) == 'U'))
                add_input_1 = permute(add_input_1.value, fliplr(1:max(2,add_input_1.rank)));
            end

        end



        function [add_input_1] = tracedPyTorchFunction(obj,add_argument1_1, add_14,isForward,predict)

            [Constant_17] = empty_model_traced_mf.ops.makeStructForConstant(int64(obj.Constant_17), int64(0), "Typed");
            [add_input_1] = empty_model_traced_mf.ops.pyElementwiseBinary(add_argument1_1, add_14, 'plus', Constant_17);
        end

    end
end

