/*
 * AUTO-GENERATED by build_v3.py — do not edit by hand.
 * Model: L=1  H=2  C=4  T_MAX=10  N_U=6  N_Y=1  bias=0
 *
 * Key optimization: SAXPY-form matrix multiply with pre-transposed weights.
 * Weight matrices stored as W_T[in_dim][out_dim] instead of W[out_dim][in_dim].
 * Inner loop: dst[i] += W_T[j*out_dim+i] * src[j]  ->  pure SAXPY,
 * which gcc maps to full-width AVX2 instructions automatically.
 *
 * API:  void gpt_forward(const float input[T_MAX*N_U], float output[T_MAX*N_Y]);
 * Compile (host):  gcc -O3 -march=native -DSTANDALONE -o gpt_model_v3 C_libs\test_l1_e4_h10.c -lm
 * Compile (SR6):   arm-none-eabi-gcc -O3 -mcpu=cortex-r52 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -DSTANDALONE -o gpt_model_v3.elf C_libs\test_l1_e4_h10.c -lm
 */

#include <math.h>
#include <string.h>

#define T_MAX       10
#define N_LAYER     1
#define N_HEAD      2
#define N_EMBD      4
#define N_U         6
#define N_Y         1
#define N_HEAD_SIZE 2
#define N_EMBD3     12
#define N_EMBD4     16

/* causal mask: CAUSAL_MASK[tq*T_MAX + tk] = 1 if tk<=tq, else 0 */
static const unsigned char CAUSAL_MASK[100] = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
    1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
    0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
    1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1
};

/*
 * Weight matrices for linear layers are stored TRANSPOSED:
 *   Original:   W    [out_dim][in_dim]
 *   Stored as:  W_T  [in_dim][out_dim]
 * This lets the SAXPY inner loop read W_T sequentially.
 * Non-linear weights (layernorm scale/bias) are NOT transposed.
 */

static const float WTE_W_T[24] = {
    -0.015202858f, -0.001127459f, 0.02391121f, -0.014613492f, -0.0081611518f, 0.0067370883f, -0.053091221f, -0.023522688f,
    -0.004007638f, -0.016870769f, -0.026331332f, -0.021277554f, 0.00063759828f, 0.010126112f, 0.0071450085f, 0.0086681908f,
    0.035612382f, -0.095915005f, 0.031030534f, -0.091462776f, -0.062096465f, 0.057909142f, -0.063715503f, 0.073607348f
};

static const float WTE_B[4] = {
    0.058367677f, 0.030636115f, -0.054198228f, 0.02715609f
};

static const float WPE_W[40] = {
    -0.0087299785f, -0.029697431f, -0.0021279927f, -0.012143246f, -0.0047960742f, -0.025560223f, 0.0042574187f, -0.0053674057f,
    -0.0087111564f, -0.028518364f, 0.0011241892f, -0.0086865267f, -0.0043971608f, -0.023047062f, 0.005950829f, -0.0044171577f,
    0.001102493f, -0.016607778f, 0.011748318f, 0.0006794699f, -0.0084706424f, -0.025159631f, 0.0024361657f, -0.009156744f,
    -0.0046420163f, -0.02019361f, 0.0064431019f, -0.0059455796f, -0.0083244042f, -0.022339348f, 0.0031113902f, -0.010225309f,
    0.0017826132f, -0.01076724f, 0.013364566f, -0.0010452595f, 0.003638457f, -0.0071142116f, 0.015573941f, -0.00011864048f
};

static const float LN1_W_0[4] = {
    1.0246791f, 0.99929321f, 1.0313125f, 1.1281726f
};

/* LN1_B_0: no bias */

static const float C_ATTN_W_T_0[48] = {
    0.27354914f, -0.26100945f, -0.15593083f, 0.098107725f, 0.36998609f, -0.34329098f, -0.35478282f, 0.16170388f,
    -0.043710317f, -0.0015748315f, -0.041905321f, 0.035670124f, -0.39546767f, 0.41872528f, 0.38674873f, -0.29064086f,
    -0.46277672f, 0.48824841f, 0.40512195f, -0.22099426f, 0.04189276f, 0.051428854f, 0.034335114f, 0.04663511f,
    0.071668632f, -0.087589003f, -0.074179187f, 0.19985732f, 0.43025118f, -0.46347174f, -0.45502394f, 0.26685238f,
    0.028515689f, -0.011486636f, 0.026697101f, -0.013998468f, -0.43378854f, 0.46213445f, 0.37704214f, -0.33459297f,
    -0.40147147f, 0.40112007f, 0.37779588f, -0.1060099f, -0.13985331f, -0.054200411f, -0.066662706f, -0.054490041f
};

/* C_ATTN_B_0: no bias */

static const float C_PROJ_W_T_0[16] = {
    -0.00037651567f, 0.016862657f, -0.052891828f, 0.029693482f, -0.03204865f, 0.0094000502f, -0.028387768f, 0.037660249f,
    -0.0024725883f, 0.044111397f, -0.023085268f, 0.014351348f, -0.033247862f, 0.015370877f, -0.0080709951f, 0.025629114f
};

/* C_PROJ_B_0: no bias */

static const float LN2_W_0[4] = {
    1.1160284f, 1.041793f, 1.0472143f, 1.1285573f
};

/* LN2_B_0: no bias */

static const float FC_W_T_0[64] = {
    -0.0059405379f, -0.066557482f, -0.0027521495f, -0.038258255f, -0.045731094f, 0.092043072f, 0.072020955f, 0.016041063f,
    -0.038225651f, 0.051057465f, -0.034951594f, 0.071339771f, 0.11875381f, 0.051121999f, -0.025109654f, 0.026804773f,
    -0.039575357f, 0.0050076051f, 0.0021912858f, -0.026094679f, 0.02494753f, 0.020683397f, 0.030092126f, 0.0051608677f,
    -0.0096236989f, -0.030448852f, 0.024437819f, -0.026921291f, -0.027042134f, -0.04297154f, -0.041036993f, -0.060523834f,
    0.060043536f, -0.019045565f, 0.016109729f, -0.0059679346f, 0.03840654f, -0.013722676f, 0.0012998031f, -0.023294128f,
    -0.014791043f, -0.03166369f, 0.0095443651f, -0.029194763f, -0.038831253f, -0.011831001f, 0.040607974f, -0.014566358f,
    0.10711829f, 0.0089933937f, 0.095269971f, 0.087684587f, 0.039549295f, -0.03166854f, -0.0097836992f, -0.093106829f,
    0.076713823f, -0.01822341f, 0.063538626f, -0.045345351f, -0.064112566f, -0.043799412f, 0.0093012638f, 0.020529471f
};

/* FC_B_0: no bias */

static const float PROJ_W_T_0[64] = {
    -0.016107783f, 0.099337988f, -0.022863662f, 0.012171893f, 0.020788245f, 0.017636016f, -0.051823925f, 0.069665305f,
    -0.0057623028f, 0.041111175f, -0.03779044f, 0.0080364281f, -0.017673217f, 0.048975822f, -0.048100051f, 0.027496748f,
    -0.0017723882f, 0.014788594f, -0.081357829f, 0.056358606f, 0.016867099f, -0.02158086f, 0.037719786f, -0.05789255f,
    -0.0082961973f, -0.041584142f, 0.02458832f, -0.031230543f, 0.05554112f, -0.083457619f, 0.0077719591f, -0.036350943f,
    0.0013448835f, 0.054042447f, -0.046450172f, 0.01316606f, -0.0033299013f, -0.010870691f, 0.038433567f, -0.062108226f,
    0.01501005f, 0.043305065f, -0.02773013f, 0.059819803f, 0.012887183f, -0.038926508f, 0.069761708f, -0.06704329f,
    0.0079617724f, -0.04542581f, 0.10921305f, -0.071724162f, 0.032193378f, -0.016113933f, 0.04859766f, -0.066289313f,
    0.00073966756f, 0.054758895f, -0.017069222f, 0.00724797f, -0.043736558f, -0.016091345f, 0.001302822f, 0.0007038886f
};

/* PROJ_B_0: no bias */

static const float LN_F_W[4] = {
    1.1749885f, 1.2394516f, 1.2418751f, 1.1345428f
};

/* LN_F_B: no bias */

static const float LM_HEAD_W_T[4] = {
    0.13315903f, 0.14555155f, -0.18074653f, 0.12698041f
};

static const float LM_HEAD_B[1] = {
    0.30587402f
};

#if !defined(__GNUC__) && !defined(__clang__)
#  define __attribute__(x)
#endif

/*
 * linear_saxpy: W_T is [in_dim][out_dim] (pre-transposed).
 * dst[t*out_dim + i] += src[t*in_dim + j] * W_T[j*out_dim + i]
 * Inner loop is a pure SAXPY — both dst and W_T row are contiguous.
 */
static void linear_saxpy(
    float * __restrict__ dst,
    const float * __restrict__ src,
    const float * __restrict__ W_T,
    const float * __restrict__ b,
    int out_dim, int in_dim)
{
    for (int t = 0; t < T_MAX; t++) {
        float       * __restrict__ d = dst + t * out_dim;
        const float * __restrict__ s = src + t * in_dim;
        if (b) { for (int i = 0; i < out_dim; i++) d[i] = b[i]; }
        else   { for (int i = 0; i < out_dim; i++) d[i] = 0.0f; }
        for (int j = 0; j < in_dim; j++) {
            const float * __restrict__ wrow = W_T + j * out_dim;
            float sv = s[j];
            for (int i = 0; i < out_dim; i++) d[i] += sv * wrow[i];
        }
    }
}

static void layernorm(
    float * __restrict__ dst,
    const float * __restrict__ src,
    const float * __restrict__ ww,
    const float * __restrict__ b,
    int C)
{
    const float eps = 1e-5f;
    for (int t = 0; t < T_MAX; t++) {
        const float * __restrict__ x = src + t * C;
        float       * __restrict__ d = dst + t * C;
        float mean = 0.0f;
        for (int i = 0; i < C; i++) mean += x[i];
        mean /= (float)C;
        float var = 0.0f;
        for (int i = 0; i < C; i++) { float v = x[i]-mean; var += v*v; }
        float inv = 1.0f / sqrtf(var / (float)C + eps);
        for (int i = 0; i < C; i++)
            d[i] = ww[i] * (x[i] - mean) * inv + (b ? b[i] : 0.0f);
    }
}

static inline float gelu(float x) {
    return 0.5f * x * (1.0f + erff(x * 0.7071067811865476f));
}

#if defined(__GNUC__) || defined(__clang__)
__attribute__((optimize("O3")))
#endif
void gpt_forward(const float input[T_MAX * N_U], float output[T_MAX * N_Y])
{
    static float x     [T_MAX * N_EMBD];
    static float normed[T_MAX * N_EMBD];
    static float tmp   [T_MAX * N_EMBD];
    static float qkv   [T_MAX * N_EMBD3];
    static float att   [N_HEAD * T_MAX * T_MAX];
    static float vacc  [T_MAX * N_EMBD];
    static float mlph  [T_MAX * N_EMBD4];

    /* embeddings: wte (SAXPY) + wpe (add) */
    linear_saxpy(x, input, WTE_W_T, WTE_B, N_EMBD, N_U);
    for (int t = 0; t < T_MAX; t++) {
        const float * __restrict__ pe = WPE_W + t * N_EMBD;
        float       * __restrict__ xt = x     + t * N_EMBD;
        for (int i = 0; i < N_EMBD; i++) xt[i] += pe[i];
    }

    /* ── block 0 ── */
    layernorm(normed, x, LN1_W_0, NULL, N_EMBD);
    linear_saxpy(qkv, normed, C_ATTN_W_T_0, NULL, N_EMBD3, N_EMBD);

    /* scaled dot-product attention */
    for (int h = 0; h < N_HEAD; h++) {
        for (int tq = 0; tq < T_MAX; tq++) {
            float * __restrict__ row = att + (h * T_MAX + tq) * T_MAX;
            const float * __restrict__ q = qkv + tq*N_EMBD3 + h*N_HEAD_SIZE;
            for (int tk = 0; tk < T_MAX; tk++) {
                if (!CAUSAL_MASK[tq * T_MAX + tk]) {
                    row[tk] = -1e30f; continue;
                }
                const float * __restrict__ k = qkv + tk*N_EMBD3 + N_EMBD + h*N_HEAD_SIZE;
                float dot = 0.0f;
                for (int d = 0; d < N_HEAD_SIZE; d++) dot += q[d] * k[d];
                row[tk] = dot * 0.70710678f;
            }
        }
    }

    /* softmax */
    for (int r = 0; r < N_HEAD * T_MAX; r++) {
        float * __restrict__ row = att + r * T_MAX;
        float mx = row[0];
        for (int i = 1; i < T_MAX; i++) if (row[i] > mx) mx = row[i];
        float s = 0.0f;
        for (int i = 0; i < T_MAX; i++) { row[i] = expf(row[i]-mx); s += row[i]; }
        float inv_s = 1.0f / s;
        for (int i = 0; i < T_MAX; i++) row[i] *= inv_s;
    }

    /* weighted value accumulation */
    memset(vacc, 0, sizeof(float) * T_MAX * N_EMBD);
    for (int h = 0; h < N_HEAD; h++) {
        for (int tq = 0; tq < T_MAX; tq++) {
            float * __restrict__ dst = vacc + tq*N_EMBD + h*N_HEAD_SIZE;
            const float * __restrict__ row = att + (h*T_MAX + tq)*T_MAX;
            for (int tk = 0; tk < T_MAX; tk++) {
                const float * __restrict__ v = qkv + tk*N_EMBD3 + 2*N_EMBD + h*N_HEAD_SIZE;
                float wt = row[tk];
                for (int d = 0; d < N_HEAD_SIZE; d++) dst[d] += wt * v[d];
            }
        }
    }

    linear_saxpy(tmp, vacc, C_PROJ_W_T_0, NULL, N_EMBD, N_EMBD);
    for (int i = 0; i < T_MAX * N_EMBD; i++) x[i] += tmp[i];

    /* MLP */
    layernorm(normed, x, LN2_W_0, NULL, N_EMBD);
    linear_saxpy(mlph, normed, FC_W_T_0, NULL, N_EMBD4, N_EMBD);
    for (int i = 0; i < T_MAX * N_EMBD4; i++) mlph[i] = gelu(mlph[i]);
    linear_saxpy(tmp, mlph, PROJ_W_T_0, NULL, N_EMBD, N_EMBD4);
    for (int i = 0; i < T_MAX * N_EMBD; i++) x[i] += tmp[i];

    layernorm(normed, x, LN_F_W, NULL, N_EMBD);
    linear_saxpy(output, normed, LM_HEAD_W_T, LM_HEAD_B, N_Y, N_EMBD);
}

#ifdef STANDALONE
#include <stdio.h>
#include <stdlib.h>

#if defined(_WIN32)
#  include <windows.h>
static double now_sec(void) {
    LARGE_INTEGER t, f;
    QueryPerformanceCounter(&t);
    QueryPerformanceFrequency(&f);
    return (double)t.QuadPart / (double)f.QuadPart;
}
#else
#  include <time.h>
static double now_sec(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}
#endif

int main(int argc, char *argv[])
{
    static float input [T_MAX * N_U];
    static float output[T_MAX * N_Y];
    if (argc == 3) {
        FILE *fin = fopen(argv[1], "rb");
        if (!fin) { perror(argv[1]); return 1; }
        if (fread(input, sizeof(float), T_MAX*N_U, fin) != (size_t)(T_MAX*N_U)) {
            fprintf(stderr, "Input file too short\n"); fclose(fin); return 1;
        }
        fclose(fin);
        gpt_forward(input, output);
        FILE *fout = fopen(argv[2], "wb");
        if (!fout) { perror(argv[2]); return 1; }
        fwrite(output, sizeof(float), T_MAX*N_Y, fout);
        fclose(fout);
        printf("done T=%d N_U=%d N_Y=%d\n", T_MAX, N_U, N_Y);
    } else {
        for (int i = 0; i < T_MAX*N_U; i++) input[i] = (float)i * 0.01f;
        int warmup = 50, runs = 500;
        for (int i = 0; i < warmup; i++) gpt_forward(input, output);
        double t0 = now_sec();
        for (int i = 0; i < runs; i++) gpt_forward(input, output);
        double elapsed = now_sec() - t0;
        printf("T_MAX=%d  L=%d  H=%d  C=%d\n", T_MAX, N_LAYER, N_HEAD, N_EMBD);
        printf("mean_ms=%.6f\n",   elapsed/runs*1e3);
        printf("fwd_per_s=%.2f\n", runs/elapsed);
    }
    return 0;
}
#endif /* STANDALONE */
