/*
 * AUTO-GENERATED by build_v3.py — do not edit by hand.
 * Model: L=1  H=2  C=2  W_MAX=10  N_U=6  N_Y=1  bias=0
 *
 * Key optimization: SAXPY-form matrix multiply with pre-transposed weights.
 * Weight matrices stored as W_T[in_dim][out_dim] instead of W[out_dim][in_dim].
 * Inner loop: dst[i] += W_T[j*out_dim+i] * src[j]  ->  pure SAXPY,
 * which gcc maps to full-width AVX2 instructions automatically.
 *
 * API:  void gpt_forward(const float input[W_MAX*N_U], float output[W_MAX*N_Y]);
 * Compile (host):  gcc -O3 -march=native -DSTANDALONE -o gpt_model_v3 C_libs\test_l1_e2_h10.c -lm
 * Compile (SR6):   arm-none-eabi-gcc -O3 -mcpu=cortex-r52 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -DSTANDALONE -o gpt_model_v3.elf C_libs\test_l1_e2_h10.c -lm
 */

#include <math.h>
#include <string.h>

#define W_MAX       10
#define N_LAYER     1
#define N_HEAD      2
#define N_EMBD      2
#define N_U         6
#define N_Y         1
#define N_HEAD_SIZE 1
#define N_EMBD3     6
#define N_EMBD4     8

/* causal mask: CAUSAL_MASK[tq*W_MAX + tk] = 1 if tk<=tq, else 0 */
static const unsigned char CAUSAL_MASK[100] = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
    1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
    0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
    1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1
};

/*
 * Weight matrices for linear layers are stored TRANSPOSED:
 *   Original:   W    [out_dim][in_dim]
 *   Stored as:  W_T  [in_dim][out_dim]
 * This lets the SAXPY inner loop read W_T sequentially.
 * Non-linear weights (layernorm scale/bias) are NOT transposed.
 */

static const float WTE_W_T[12] = {
    -0.044485282f, 0.049904391f, 0.039517816f, -0.010056438f, -0.020034168f, -0.010989342f, 0.024293076f, 0.014587094f,
    -0.15990947f, 0.11130136f, 0.13909687f, -0.13053969f
};

static const float WTE_B[2] = {
    0.034593932f, -0.034594126f
};

static const float WPE_W[20] = {
    -0.026292544f, 0.022454036f, -0.0071365046f, 0.04237777f, 0.00086061645f, 0.050693158f, -0.0077908356f, 0.042192213f,
    -0.034454249f, 0.015590617f, -0.013671903f, 0.036584176f, -0.020113662f, 0.030151982f, -0.03387548f, 0.016367065f,
    -0.041269459f, 0.0090092979f, -0.020151421f, 0.030272875f
};

static const float LN1_W_0[2] = {
    1.3877929f, 1.3951154f
};

/* LN1_B_0: no bias */

static const float C_ATTN_W_T_0[12] = {
    0.48789886f, 0.35372323f, 0.47971809f, 0.36913648f, -0.043610722f, 0.027602216f, -0.48707393f, -0.35837871f,
    -0.50675368f, -0.34515622f, 0.036932651f, 0.0068416228f
};

/* C_ATTN_B_0: no bias */

static const float C_PROJ_W_T_0[4] = {
    0.069550119f, -0.032874644f, 0.016564796f, -0.0019046463f
};

/* C_PROJ_B_0: no bias */

static const float LN2_W_0[2] = {
    1.1040591f, 1.1270003f
};

/* LN2_B_0: no bias */

static const float FC_W_T_0[16] = {
    -0.077969849f, -0.01463043f, -0.023771688f, 0.014292007f, 0.039909918f, -0.016683707f, -0.010804689f, 0.0046346858f,
    0.078738712f, -0.015580063f, 0.040461183f, 0.0095350267f, -0.0080519132f, 0.0017025878f, 0.058262106f, 0.0097542144f
};

/* FC_B_0: no bias */

static const float PROJ_W_T_0[16] = {
    0.036221664f, -0.026226703f, 0.0037181741f, 0.00364017f, 0.01542309f, -0.020381913f, -0.0074123344f, 0.01202712f,
    0.0065378086f, -0.012743151f, 0.0035294865f, 0.00092566875f, 0.024749668f, -0.010953229f, -0.017911294f, 0.013214323f
};

/* PROJ_B_0: no bias */

static const float LN_F_W[2] = {
    1.1638299f, 1.2881409f
};

/* LN_F_B: no bias */

static const float LM_HEAD_W_T[2] = {
    0.15142292f, -0.18105508f
};

static const float LM_HEAD_B[1] = {
    0.50999194f
};

#if !defined(__GNUC__) && !defined(__clang__)
#  define __attribute__(x)
#endif

/*
 * linear_saxpy: W_T is [in_dim][out_dim] (pre-transposed).
 * dst[t*out_dim + i] += src[t*in_dim + j] * W_T[j*out_dim + i]
 * Inner loop is a pure SAXPY — both dst and W_T row are contiguous.
 */
static void linear_saxpy(
    float * __restrict__ dst,
    const float * __restrict__ src,
    const float * __restrict__ W_T,
    const float * __restrict__ b,
    int out_dim, int in_dim)
{
    for (int t = 0; t < W_MAX; t++) {
        float       * __restrict__ d = dst + t * out_dim;
        const float * __restrict__ s = src + t * in_dim;
        if (b) { for (int i = 0; i < out_dim; i++) d[i] = b[i]; }
        else   { for (int i = 0; i < out_dim; i++) d[i] = 0.0f; }
        for (int j = 0; j < in_dim; j++) {
            const float * __restrict__ wrow = W_T + j * out_dim;
            float sv = s[j];
            for (int i = 0; i < out_dim; i++) d[i] += sv * wrow[i];
        }
    }
}

static void layernorm(
    float * __restrict__ dst,
    const float * __restrict__ src,
    const float * __restrict__ ww,
    const float * __restrict__ b,
    int C)
{
    const float eps = 1e-5f;
    for (int t = 0; t < W_MAX; t++) {
        const float * __restrict__ x = src + t * C;
        float       * __restrict__ d = dst + t * C;
        float mean = 0.0f;
        for (int i = 0; i < C; i++) mean += x[i];
        mean /= (float)C;
        float var = 0.0f;
        for (int i = 0; i < C; i++) { float v = x[i]-mean; var += v*v; }
        float inv = 1.0f / sqrtf(var / (float)C + eps);
        for (int i = 0; i < C; i++)
            d[i] = ww[i] * (x[i] - mean) * inv + (b ? b[i] : 0.0f);
    }
}

static inline float gelu(float x) {
    return 0.5f * x * (1.0f + erff(x * 0.7071067811865476f));
}

#if defined(__GNUC__) || defined(__clang__)
__attribute__((optimize("O3")))
#endif
void gpt_forward(const float input[W_MAX * N_U], float output[W_MAX * N_Y])
{
    static float x     [W_MAX * N_EMBD];
    static float normed[W_MAX * N_EMBD];
    static float tmp   [W_MAX * N_EMBD];
    static float qkv   [W_MAX * N_EMBD3];
    static float att   [N_HEAD * W_MAX * W_MAX];
    static float vacc  [W_MAX * N_EMBD];
    static float mlph  [W_MAX * N_EMBD4];

    /* embeddings: wte (SAXPY) + wpe (add) */
    linear_saxpy(x, input, WTE_W_T, WTE_B, N_EMBD, N_U);
    for (int t = 0; t < W_MAX; t++) {
        const float * __restrict__ pe = WPE_W + t * N_EMBD;
        float       * __restrict__ xt = x     + t * N_EMBD;
        for (int i = 0; i < N_EMBD; i++) xt[i] += pe[i];
    }

    /* ── block 0 ── */
    layernorm(normed, x, LN1_W_0, NULL, N_EMBD);
    linear_saxpy(qkv, normed, C_ATTN_W_T_0, NULL, N_EMBD3, N_EMBD);

    /* scaled dot-product attention */
    for (int h = 0; h < N_HEAD; h++) {
        for (int tq = 0; tq < W_MAX; tq++) {
            float * __restrict__ row = att + (h * W_MAX + tq) * W_MAX;
            const float * __restrict__ q = qkv + tq*N_EMBD3 + h*N_HEAD_SIZE;
            for (int tk = 0; tk < W_MAX; tk++) {
                if (!CAUSAL_MASK[tq * W_MAX + tk]) {
                    row[tk] = -1e30f; continue;
                }
                const float * __restrict__ k = qkv + tk*N_EMBD3 + N_EMBD + h*N_HEAD_SIZE;
                float dot = 0.0f;
                for (int d = 0; d < N_HEAD_SIZE; d++) dot += q[d] * k[d];
                row[tk] = dot * 1.0f;
            }
        }
    }

    /* softmax */
    for (int r = 0; r < N_HEAD * W_MAX; r++) {
        float * __restrict__ row = att + r * W_MAX;
        float mx = row[0];
        for (int i = 1; i < W_MAX; i++) if (row[i] > mx) mx = row[i];
        float s = 0.0f;
        for (int i = 0; i < W_MAX; i++) { row[i] = expf(row[i]-mx); s += row[i]; }
        float inv_s = 1.0f / s;
        for (int i = 0; i < W_MAX; i++) row[i] *= inv_s;
    }

    /* weighted value accumulation */
    memset(vacc, 0, sizeof(float) * W_MAX * N_EMBD);
    for (int h = 0; h < N_HEAD; h++) {
        for (int tq = 0; tq < W_MAX; tq++) {
            float * __restrict__ dst = vacc + tq*N_EMBD + h*N_HEAD_SIZE;
            const float * __restrict__ row = att + (h*W_MAX + tq)*W_MAX;
            for (int tk = 0; tk < W_MAX; tk++) {
                const float * __restrict__ v = qkv + tk*N_EMBD3 + 2*N_EMBD + h*N_HEAD_SIZE;
                float wt = row[tk];
                for (int d = 0; d < N_HEAD_SIZE; d++) dst[d] += wt * v[d];
            }
        }
    }

    linear_saxpy(tmp, vacc, C_PROJ_W_T_0, NULL, N_EMBD, N_EMBD);
    for (int i = 0; i < W_MAX * N_EMBD; i++) x[i] += tmp[i];

    /* MLP */
    layernorm(normed, x, LN2_W_0, NULL, N_EMBD);
    linear_saxpy(mlph, normed, FC_W_T_0, NULL, N_EMBD4, N_EMBD);
    for (int i = 0; i < W_MAX * N_EMBD4; i++) mlph[i] = gelu(mlph[i]);
    linear_saxpy(tmp, mlph, PROJ_W_T_0, NULL, N_EMBD, N_EMBD4);
    for (int i = 0; i < W_MAX * N_EMBD; i++) x[i] += tmp[i];

    layernorm(normed, x, LN_F_W, NULL, N_EMBD);
    linear_saxpy(output, normed, LM_HEAD_W_T, LM_HEAD_B, N_Y, N_EMBD);
}

#ifdef STANDALONE
#include <stdio.h>
#include <stdlib.h>

#if defined(_WIN32)
#  include <windows.h>
static double now_sec(void) {
    LARGE_INTEGER t, f;
    QueryPerformanceCounter(&t);
    QueryPerformanceFrequency(&f);
    return (double)t.QuadPart / (double)f.QuadPart;
}
#else
#  include <time.h>
static double now_sec(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}
#endif

int main(int argc, char *argv[])
{
    static float input [W_MAX * N_U];
    static float output[W_MAX * N_Y];
    if (argc == 3) {
        FILE *fin = fopen(argv[1], "rb");
        if (!fin) { perror(argv[1]); return 1; }
        if (fread(input, sizeof(float), W_MAX*N_U, fin) != (size_t)(W_MAX*N_U)) {
            fprintf(stderr, "Input file too short\n"); fclose(fin); return 1;
        }
        fclose(fin);
        gpt_forward(input, output);
        FILE *fout = fopen(argv[2], "wb");
        if (!fout) { perror(argv[2]); return 1; }
        fwrite(output, sizeof(float), W_MAX*N_Y, fout);
        fclose(fout);
        printf("done T=%d N_U=%d N_Y=%d\n", W_MAX, N_U, N_Y);
    } else {
        for (int i = 0; i < W_MAX*N_U; i++) input[i] = (float)i * 0.01f;
        int warmup = 50, runs = 500;
        for (int i = 0; i < warmup; i++) gpt_forward(input, output);
        double t0 = now_sec();
        for (int i = 0; i < runs; i++) gpt_forward(input, output);
        double elapsed = now_sec() - t0;
        printf("W_MAX=%d  L=%d  H=%d  C=%d\n", W_MAX, N_LAYER, N_HEAD, N_EMBD);
        printf("mean_ms=%.6f\n",   elapsed/runs*1e3);
        printf("fwd_per_s=%.2f\n", runs/elapsed);
    }
    return 0;
}
#endif /* STANDALONE */
